package risingdeathx2.spigot.wolfcore.classes;

public class ArgumentType {
    public static final ArgumentType GAMEMODE = new ArgumentType();
    public static final ArgumentType INTEGER = new ArgumentType();
    public static final ArgumentType DOUBLE = new ArgumentType();
    public static final ArgumentType BOOLEAN = new ArgumentType();
    public static final ArgumentType PLAYER = new ArgumentType();
    public static final ArgumentType EXCLUSIVEPLAYER = new ArgumentType();
    public static final ArgumentType OTHERPLAYER = new ArgumentType();
    public static final ArgumentType EXCLUSIVEOTHERPLAYER = new ArgumentType();
    public static final ArgumentType WORLD = new ArgumentType();
    public static final ArgumentType LOCATION = new ArgumentType();
    public static final ArgumentType ITEMSTACK = new ArgumentType();
    public static final ArgumentType ENTITY = new ArgumentType();
    public static final ArgumentType VECTOR = new ArgumentType();
    public static final ArgumentType BLOCK = new ArgumentType();
    public static final ArgumentType BLOCKSTATE = new ArgumentType();
    public static final ArgumentType COMMAND = new ArgumentType();
    public static final ArgumentType COLOR = new ArgumentType();
    public static final ArgumentType COMPONENT = new ArgumentType();
    public static final ArgumentType MESSAGE = new ArgumentType();
    public static final ArgumentType POTIONEFFECT = new ArgumentType();
    public static final ArgumentType SOUND = new ArgumentType();
    public static final ArgumentType PARTICLE = new ArgumentType();
    public static final ArgumentType ENCHANTMENT = new ArgumentType();
    public static final ArgumentType ENTITYTYPE = new ArgumentType();
    public static final ArgumentType MATERIAL = new ArgumentType();
    public static final ArgumentType RAYTRACE = new ArgumentType();
    public static final ArgumentType UUID = new ArgumentType();
    public static final ArgumentType ATTRIBUTE = new ArgumentType();
    public static final ArgumentType AXIS = new ArgumentType();
    public static final ArgumentType HAND = new ArgumentType();
    public static final ArgumentType INVENTORY = new ArgumentType();
    public static final ArgumentType MINECART = new ArgumentType();
    public static final ArgumentType POTION = new ArgumentType();
    public static final ArgumentType RAIL = new ArgumentType();
    public static final ArgumentType ROTATION = new ArgumentType();
    public static final ArgumentType VILLAGERPROFESSION = new ArgumentType();
    public static final ArgumentType BLOCKDATA = new ArgumentType();
    public static final ArgumentType CATALOGTYPE = new ArgumentType();
    public static final ArgumentType CATALOG = new ArgumentType();
    public static final ArgumentType CATALOGKEY = new ArgumentType();
    public static final ArgumentType CATALOGTYPEKEY = new ArgumentType();
    public static final ArgumentType CATALOGTYPEVALUE = new ArgumentType();
}
