main: risingdeathx2.spigot.wolfcore.core
name: wolf-core
version: 0.1
api-version: 1.20
commands:
  database:
    description: Database Management
    aliases: [db]
  help:
    description: Help Command
  mute:
    description: Mute Command
  lag:
    description: Lag Command
  delhome:
    description: Delete Home Command
  sethome:
    description: Set Home Command
  home:
    description: Home Command
  kickall:
    description: Kick All Command
  kick:
    description: Kick Command
  max:
    description: Max Command
  whois:
    description: Whois Command
  tptoggle:
    description: Teleport Toggle Command
  gamemode:
    description: Gamemode Command
    aliases: [gm]
  gms:
    description: Gamemode Alias
    aliases: [gmc, gma, gmsp]
  teleport:
    description: Teleport Command
    aliases: [tp]
  teleportall:
    description: Teleport All Command
    aliases: [tpall]
  teleporthere:
    description: Teleport Here Command
    aliases: [tphere]
  teleportask:
    description: Teleport Ask Command
    aliases: [tpa,tpahere,teleportaskhere]
  teleportaccept:
    description: Teleport Accept Command
    aliases: [tpaccept]
  teleportdeny:
    description: Teleport Deny Command
    aliases: [tpdeny]
  tppos:
    description: Teleport Position Command
  warp:
    description: Warp Command
  warps:
    description: Warps List
  warpinfo:
    description: Warp Info Command
  setwarp:
    description: Set Warp Command
  delwarp:
    description: Delete Warp Command
  ban:
    description: Ban Command
  unban:
    description: Unban Command
  banip:
    description: Ban IP Command
  unbanip:
    description: Unban IP Command
  banlist:
    description: Ban List Command
  tempban:
    description: Temp Ban Command
  tempbanip:
    description: Temp Ban IP Command
  unmute:
    description: Unmute Command
  tempmute:
    description: Temp Mute Command