main: com.wolfco.main.Core
name: wolf-core
version: 0.1
api-version: 1.21
commands:
  offlineteleport:
    aliases: [ otp ]
    description: Offline Teleport Command
  kill:
    description: Kill Command
  back:
    description: Back Command
  ban:
    description: Ban Command
  banip:
    description: Ban IP Command
  banlist:
    description: Ban List Command
  database:
    aliases: [ db ]
    description: Database Management
  delhome:
    description: Delete Home Command
  delwarp:
    description: Delete Warp Command
  enchant:
    description: Enchant Command
  fly:
    description: Fly Command
  flyspeed:
    description: Fly Speed Command
  gamemode:
    aliases: [ gm ]
    description: Gamemode Command
  gms:
    aliases: [ gmc, gma, gmsp ]
    description: Gamemode Alias
  help:
    description: Help Command
  home:
    description: Home Command
  lag:
    description: Lag Command
  max:
    description: Max Command
  reach:
    description: Reach Command
  sethome:
    description: Set Home Command
  setwarp:
    description: Set Warp Command
  speed:
    description: Speed Command
  teleport:
    aliases: [ tp ]
    description: Teleport Command
  teleportaccept:
    aliases: [ tpaccept ]
    description: Teleport Accept Command
  teleportall:
    aliases: [ tpall ]
    description: Teleport All Command
  teleportask:
    aliases: [ tpa, tpahere, teleportaskhere ]
    description: Teleport Ask Command
  teleportdeny:
    aliases: [ tpdeny ]
    description: Teleport Deny Command
  teleporthere:
    aliases: [ tphere ]
    description: Teleport Here Command
  test:
    description: Test Command
  top:
    description: Top Command
  tppos:
    description: Teleport Position Command
  tptoggle:
    description: Teleport Toggle Command
  walkspeed:
    description: Walk Speed Command
  warp:
    description: Warp Command
  warpinfo:
    description: Warp Info Command
  warps:
    description: Warps List
  world:
    description: World Command

